### ISSUE TITLE
Gostaria de saber um pouco mais sobre o projeto

### ISSUE THREAD

**Issue by instrutorsenai2022a** [Naiany04/Lab03#1]
Este projeto vai atender que tipo de público?
Quando será lançado?
Qual o orçamento para o projeto?

**Comment by DiamexX** [comment]
3 mil dolar

**Comment by GustaSil** [comment]
qual a data de lançamento

**Comment by MariaEduarda2004** [comment]
dia 14

**Comment by MariaEduarda2004** [comment]
500

**Comment by alesantos010** [comment]
Qual o objetivo do seu projeto?

**Comment by joaonetopereira** [comment]
Rola um desconto

**Comment by MariaEduarda2004** [comment]
nao

**Comment by DiamexX** [comment]
aceita pix?

**Comment by instrutorsenai2022a** [comment]
# Quem chegou até aqui?

_aqui também pode se usar o markdown_

**Comment by Raimundo2022** [comment]
se os Dinossauros morreram a milhões de anos, como o mundo so tem 2022 ?

**Comment by joaonetopereira** [comment]
safsaffff
